"use client";

import Link from "next/link";
import { LanguageSwitcher, useLanguage, type Locale } from "../../i18n/i18n";

type LegalKind = "privacy" | "terms" | "risk";
type Copy = { title: string; kicker: string; sections: Array<[string, string]> };

const copy: Record<Locale, Record<LegalKind, Copy>> = {
  vi: {
    privacy: { title: "Chính sách dữ liệu và quyền riêng tư", kicker: "DATA MINIMIZATION", sections: [["1. Dữ liệu được xử lý", "SkillBridge xử lý địa chỉ ví công khai, hồ sơ, tư cách thành viên tổ chức, challenge, bài nộp, file evidence, hash file, kết quả đánh giá, quyết định reviewer, credential và nhật ký bảo mật. Chúng tôi không yêu cầu hoặc lưu seed phrase/private key."], ["2. Mục đích", "Dữ liệu được dùng để xác thực ví, vận hành challenge, đánh giá evidence, phát hành credential, kiểm tra cơ hội, xử lý sự cố và đo hiệu quả pilot. AI chỉ nhận nội dung cần thiết cho lượt đánh giá; kết quả AI luôn cần reviewer phê duyệt."], ["3. On-chain và off-chain", "Evidence và thông tin nhận dạng chi tiết nằm off-chain. Solana Devnet chỉ nhận claim tối thiểu như ví, schema, điểm, hash evidence, hạn dùng và trạng thái. Dữ liệu blockchain công khai và không thể xóa như dữ liệu cơ sở dữ liệu."], ["4. Chia sẻ và quyền truy cập", "Doanh nghiệp chỉ thấy dữ liệu thuộc challenge hoặc credential được trình cho cơ hội. Reviewer chỉ thấy bài được giao cho đơn vị mình. Nhà cung cấp hạ tầng xử lý dữ liệu trong phạm vi cần thiết để cung cấp dịch vụ."], ["5. Dữ liệu cash-out pilot", "Cash-out Devnet chỉ nhận dữ liệu tài khoản thử nghiệm. Server token hóa số tài khoản, chỉ lưu mã ngân hàng, bốn số cuối và tên đã che; không lưu số tài khoản hoặc tên đầy đủ. Khi tích hợp payout thật, dữ liệu KYC/ngân hàng phải do đối tác được cấp phép thu thập qua luồng hosted hoặc tokenized."], ["6. Lưu giữ và quyền của bạn", "Trong pilot, evidence thô dự kiến được giữ tối đa 180 ngày sau khi challenge đóng; audit và sự kiện bảo mật tối đa 12 tháng. Bạn có thể yêu cầu xem, sửa hoặc xóa dữ liệu off-chain không còn cần thiết tại pilot@skillbridge.vn."]] },
    terms: { title: "Điều khoản sử dụng pilot", kicker: "REAL PRODUCT · DEVNET", sections: [["1. Phạm vi pilot", "SkillBridge là sản phẩm proof-of-skill đang pilot tại Việt Nam. Transaction chạy trên Solana Devnet; token Devnet không có giá trị tiền tệ và môi trường có thể được reset."], ["2. Danh tính ví", "Bạn chịu trách nhiệm bảo vệ ví và thiết bị. Chữ ký xác minh ví không gửi transaction hoặc chuyển tài sản. SkillBridge không bao giờ yêu cầu seed phrase."], ["3. Nội dung và tính trung thực", "Bạn chỉ nộp nội dung mình có quyền sử dụng, không tải mã độc hoặc dữ liệu trái phép, và không thao túng AI/reviewer. Bạn giữ quyền với sản phẩm và cấp quyền giới hạn để hệ thống xử lý cho challenge."], ["4. AI và human review", "AI tạo bản nháp có dẫn chứng, không phải quyết định cuối. Reviewer có thể phê duyệt, từ chối hoặc yêu cầu sửa. Credential không bảo đảm việc làm, học bổng hay tuyển chọn."], ["5. Credential và tổ chức", "Credential gắn với ví, có thể hết hạn hoặc bị issuer thu hồi khi có sai sót, gian lận hay vi phạm. Người tạo tổ chức phải xác nhận mình có thẩm quyền phù hợp."]] },
    risk: { title: "Công bố rủi ro và giới hạn", kicker: "RISK DISCLOSURE", sections: [["Blockchain", "Devnet có thể gián đoạn, reset hoặc thay đổi trạng thái; Explorer và RPC có thể chậm. Transaction đã xác nhận là công khai. Không đưa PII, bí mật kinh doanh hoặc tài liệu gốc lên chain."], ["AI", "Mô hình có thể trích xuất sai, bỏ sót evidence hoặc thiên lệch. Hệ thống dùng structured output, citation validation, prompt-injection checks và human approval nhưng không loại bỏ hoàn toàn rủi ro."], ["Cash-out USDC → VND", "USDC được gửi trong cash-out pilot là tài sản Devnet không có giá trị thật. Tỷ giá, phí, tài khoản nhận và chứng từ VND là dữ liệu thử nghiệm; không có chuyển khoản ngân hàng. Mainnet/VND chỉ được bật sau khi có đối tác off-ramp được cấp phép, KYC/AML, quote thực thi và webhook đối soát."], ["Credential", "Credential chứng minh một issuer đã phê duyệt kết quả theo schema tại một thời điểm; không phải bằng cấp pháp lý, chứng khoán, token đầu tư hoặc cam kết tuyển dụng."], ["Vận hành pilot", "Dịch vụ có thể tạm dừng để sửa lỗi và chưa có SLA production. Không dùng pilot cho quyết định nghiêm trọng nếu thiếu quy trình kiểm tra và khiếu nại độc lập."]] },
  },
  en: {
    privacy: { title: "Data and privacy policy", kicker: "DATA MINIMIZATION", sections: [["1. Data we process", "SkillBridge processes public wallet addresses, profiles, organization memberships, challenges, submissions, evidence files, file hashes, assessments, reviewer decisions, credentials and security logs. We never request or store seed phrases or private keys."], ["2. Purpose", "Data supports wallet authentication, challenge operations, evidence assessment, credential issuance, opportunity checks, incident handling and pilot measurement. AI receives only the content needed for an assessment; every AI result requires reviewer approval."], ["3. On-chain and off-chain", "Evidence and detailed identity information stay off-chain. Solana Devnet receives only minimum claims such as wallet, schema, score, evidence hash, expiry and status. Blockchain data is public and cannot be deleted like a database record."], ["4. Sharing and access", "Businesses see only data belonging to a challenge or credential presented for an opportunity. Reviewers see submissions assigned to their organization. Infrastructure providers process data only as needed to provide the service."], ["5. Pilot cash-out data", "Devnet cash-out accepts test beneficiary data only. The server tokenizes the account number and stores only the bank code, last four digits and a masked name; it does not store the full account number or name. A real payout integration must use a licensed partner's hosted or tokenized KYC/bank flow."], ["6. Retention and your rights", "During the pilot, raw evidence is expected to be retained for up to 180 days after a challenge closes; audit and security events for up to 12 months. Request access, correction or deletion of unnecessary off-chain data at pilot@skillbridge.vn."]] },
    terms: { title: "Pilot terms of use", kicker: "REAL PRODUCT · DEVNET", sections: [["1. Pilot scope", "SkillBridge is a proof-of-skill product piloted in Vietnam. Transactions run on Solana Devnet; Devnet tokens have no monetary value and the environment may reset."], ["2. Wallet identity", "You are responsible for protecting your wallet and device. The wallet verification signature sends no transaction and transfers no assets. SkillBridge will never ask for a seed phrase."], ["3. Content and integrity", "Submit only content you have the right to use. Do not upload malware, unauthorized data or content intended to manipulate AI or reviewers. You retain your product rights and grant a limited processing license for the challenge."], ["4. AI and human review", "AI creates an evidence-linked draft, not the final decision. Reviewers may approve, reject or request changes. A credential does not guarantee employment, a scholarship or selection."], ["5. Credentials and organizations", "Credentials are wallet-bound and may expire or be revoked by a valid issuer for errors, fraud or policy violations. Organization creators must confirm their authority."]] },
    risk: { title: "Risk disclosure and limitations", kicker: "RISK DISCLOSURE", sections: [["Blockchain", "Devnet may be interrupted, reset or changed; Explorer and RPC may be slow. Confirmed transactions are public. Do not put PII, business secrets or original documents on-chain."], ["AI", "Models may extract incorrectly, miss evidence or be biased. The system uses structured output, citation validation, prompt-injection checks and human approval, but cannot eliminate all risk."], ["USDC → VND cash-out", "USDC sent in the cash-out pilot is a valueless Devnet asset. The rate, fees, beneficiary and VND receipt are test data; no bank transfer occurs. Mainnet/VND stays disabled until a licensed off-ramp partner provides KYC/AML, an executable quote and signed reconciliation webhooks."], ["Credential", "A credential shows that an issuer approved a result under a schema at a point in time; it is not a legal degree, security, investment token or hiring promise."], ["Pilot operations", "The service may pause for fixes and has no production SLA. Do not use the pilot for high-impact decisions without independent checks and an appeals process."]] },
  },
};

export function LocalizedLegalPage({ kind }: { kind: LegalKind }) {
  const { locale, t } = useLanguage();
  const page = copy[locale][kind];
  return <main className="legal-page"><header className="auth-header page-shell"><Link className="wordmark" href="/" aria-label="SkillBridge Vietnam"><span className="wordmark-mark" aria-hidden="true">S</span><span>SkillBridge</span><small>VIETNAM</small></Link><div className="topbar-actions"><LanguageSwitcher /><Link className="text-link" href="/auth">{t("common.home")} →</Link></div></header><article className="legal-document page-shell"><div className="eyebrow"><span /> {page.kicker}</div><h1>{page.title}</h1><p className="legal-updated">{locale === "vi" ? "Phiên bản pilot · cập nhật ngày 25/08/2026" : "Pilot version · updated 25/08/2026"}</p>{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</article></main>;
}
