"use client";
import {apiFetch} from "../../lib/api-fetch";
import {WalletPaymentButton} from "../../components/wallet/wallet-payment-button";
import { useEffect, useState } from "react";
import { useLanguage } from "../../i18n/i18n";
import { ContentSkeleton, LoadFailure } from "../../components/feedback/loading-ui";
type Membership = { organization_id: string; organization_name: string; organization_kind: string; role: string };
type TalentOption = { user_id: string; display_name: string | null; headline: string; wallet_address: string | null };
type Contract = { is_freelancer:boolean;can_manage:boolean;id:string; title:string; description:string; total_amount_usdc:string; status:string; organization_name:string; freelancer_name:string|null; milestones:Array<{id:string;title:string;amount_usdc:string;status:string;payment_intent?:string;payment_tx?:string}> };
export function ContractsWorkspace({ memberships }: { memberships: Membership[] }) {
  const { t,locale } = useLanguage();
  const vi=locale==="vi";const [busy,setBusy]=useState(false);const [signature,setSignature]=useState(""); const [items,setItems]=useState<Contract[]>([]); const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState(false); const [profiles,setProfiles]=useState<TalentOption[]>([]); const [organizationId,setOrganizationId]=useState(memberships.find((m)=>m.organization_kind==="business")?.organization_id??""); const [freelancerUserId,setFreelancerUserId]=useState(""); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [total,setTotal]=useState(""); const [milestoneTitle,setMilestoneTitle]=useState(""); const [milestoneAmount,setMilestoneAmount]=useState(""); const [notice,setNotice]=useState<string|null>(null);
  async function load(){const r=await apiFetch("/api/contracts",{cache:"no-store"});if(r.ok)setItems(((await r.json()) as {contracts:Contract[]}).contracts)} useEffect(()=>{let active=true;Promise.all([apiFetch("/api/contracts",{cache:"no-store"}),apiFetch("/api/talent",{cache:"no-store"})]).then(async([contracts,talent])=>{if(!contracts.ok||!talent.ok)throw new Error("load");const contractData=await contracts.json() as {contracts:Contract[]};const talentData=await talent.json() as {profiles:TalentOption[]};if(active){setItems(contractData.contracts);setProfiles(talentData.profiles)}}).catch(()=>{if(active)setLoadError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  async function create(){if(busy)return;setBusy(true);try{const r=await apiFetch("/api/contracts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,freelancerUserId,title,description,totalAmountUsdc:total,milestones:[{title:milestoneTitle,amountUsdc:milestoneAmount}]})});const d=await r.json() as {error?:string};setNotice(r.ok?t("contract.created"):d.error??t("contract.error"));if(r.ok){setTitle("");setDescription("");setTotal("");setMilestoneTitle("");setMilestoneAmount("");await load()}}catch(e){setNotice(String(e));}finally{setBusy(false);}}
  async function act(id:string,action:string,milestoneId?:string,txSignature?:string){
    setBusy(true);
    try {
      const r=await apiFetch(`/api/contracts/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,milestoneId,signature:txSignature})});
      const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??t("contract.error"));
      setNotice(t("contract.updated"));await load();return {status:"funded" as const};
    }catch(e){setNotice(e instanceof Error?e.message:String(e));throw e;}finally{setBusy(false);}
  }
  if(loading)return <div id="workspace-main" tabIndex={-1} className="workspace-product-content"><ContentSkeleton delayed variant="list"/></div>;
  if(loadError)return <div id="workspace-main" tabIndex={-1} className="workspace-product-content"><LoadFailure/></div>;
  return <div id="workspace-main" tabIndex={-1} className="workspace-product-content"><div className="app-welcome"><div><span>{t("contract.kicker")}</span><h1>{t("contract.title")}</h1><p>{t("contract.description")}</p></div><div className="identity-card"><small>{t("contract.count")}</small><strong className="metric-number">{items.length}</strong><b>{t("contract.devnetMode")}</b></div></div><section className="app-panel"><div><span className="panel-kicker">{t("contract.new")}</span><h2>{t("contract.create")}</h2><p>{t("contract.createDescription")}</p></div><div className="stack-form"><label>{t("contract.selectOrg")}<select value={organizationId} onChange={(e)=>setOrganizationId(e.target.value)}><option value="">{t("contract.selectOrg")}</option>{memberships.filter((m)=>m.organization_kind==="business").map((m)=><option value={m.organization_id} key={m.organization_id}>{m.organization_name}</option>)}</select></label><label>{t("contract.freelancerLabel")}<select value={freelancerUserId} onChange={(e)=>setFreelancerUserId(e.target.value)}><option value="">{profiles.length ? t("contract.selectFreelancer") : t("contract.noFreelancers")}</option>{profiles.map((profile)=><option value={profile.user_id} key={profile.user_id}>{profile.display_name || profile.wallet_address?.slice(0, 10) || profile.user_id.slice(0, 8)}{profile.headline ? ` · ${profile.headline}` : ""}</option>)}</select></label><input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder={t("contract.titlePlaceholder")} /><textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder={t("contract.descriptionPlaceholder")} /><div className="invoice-form-grid"><input value={total} onChange={(e)=>setTotal(e.target.value)} placeholder={t("contract.totalPlaceholder")} /><input value={milestoneTitle} onChange={(e)=>setMilestoneTitle(e.target.value)} placeholder={t("contract.milestoneTitle")} /><input value={milestoneAmount} onChange={(e)=>setMilestoneAmount(e.target.value)} placeholder={t("contract.milestoneAmount")} /></div><details className="technical-details contract-advanced"><summary>{t("contract.advancedManual")}</summary><input value={freelancerUserId} onChange={(e)=>setFreelancerUserId(e.target.value)} placeholder={t("contract.freelancerAdvancedPlaceholder")} /></details><button className="button button-primary" disabled={busy||!organizationId||!freelancerUserId||!title||!total} onClick={()=>void create()}>{t("contract.createButton")}</button></div></section><section className="talent-grid">{items.map((item)=><article className="app-panel" key={item.id}><div className="entity-top"><span>{item.organization_name}</span><b>{item.status}</b></div><h2>{item.title}</h2><p>{item.description}</p><div className="entity-tags">{item.milestones.map((m)=><span key={m.id}>{m.title} · {m.amount_usdc} USDC · {m.status}</span>)}</div>{item.status==="active" && item.milestones.map(m=><section key={m.id} className="escrow-action">
        <h3>{m.title}</h3>
        {item.is_freelancer && m.status==="pending" && <button className="button button-secondary" disabled={busy} onClick={()=>void act(item.id,"submit",m.id).catch(()=>{})}>{vi?"Gửi nghiệm thu":"Submit milestone"}</button>}
        {item.can_manage && m.status==="submitted" && <button className="button button-secondary" disabled={busy} onClick={()=>void act(item.id,"approve",m.id).catch(()=>{})}>{vi?"Duyệt nghiệm thu":"Approve milestone"}</button>}
        {item.can_manage && m.status==="approved" && <>
          {m.payment_intent && <WalletPaymentButton milestoneId={m.id} label={vi?"Thanh toán USDC":"Pay USDC"} onSubmitted={sig=>act(item.id,"pay",m.id,sig)}/>}
          <label>{vi?"Đã chuyển? Dán mã giao dịch":"Already paid? Paste transaction ID"}<input value={signature} onChange={e=>setSignature(e.target.value.trim())}/></label>
          <button className="button button-secondary" disabled={busy||!signature} onClick={()=>void act(item.id,"pay",m.id,signature).catch(()=>{})}>{vi?"Xác minh thanh toán":"Verify payment"}</button>
        </>}
        {m.status==="paid" && m.payment_tx && <a href={`https://explorer.solana.com/tx/${m.payment_tx}?cluster=devnet`} target="_blank" rel="noreferrer">{vi?"Xem giao dịch":"View transaction"}</a>}
      </section>)}{item.is_freelancer&&item.status==="proposed"&&<button className="button button-primary" onClick={()=>void act(item.id,"accept").catch(()=>{})}>{t("contract.accept")}</button>}</article>)}</section>{notice&&<p className="app-notice" role="status">{notice}</p>}</div>;
}
