"use client";

import { useEffect, useState } from "react";
import { useLanguage } from "./i18n";

type CashoutSession = { id: string; amount_usdc: string; estimated_vnd: string; fee_vnd: string; net_vnd: string; provider_reference: string; status: string; created_at: string };
type Quote = { id: string; amountUsdc: string; estimatedVnd: number; feeVnd: number; netVnd: number; rate: number; providerReference: string; status: string };
function vnd(value: string | number) { return new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(Number(value)); }

export function CashoutWorkspace() {
  const { locale } = useLanguage(); const vi = locale === "vi";
  const [amount, setAmount] = useState(""); const [quote, setQuote] = useState<Quote | null>(null); const [history, setHistory] = useState<CashoutSession[]>([]); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/cashout", { cache: "no-store" }); if (response.ok) setHistory(((await response.json()) as { sessions: CashoutSession[] }).sessions); }
  useEffect(() => {
    let active = true;
    fetch("/api/cashout", { cache: "no-store" })
      .then((response) => response.ok ? response.json() as Promise<{ sessions: CashoutSession[] }> : { sessions: [] })
      .then((data) => { if (active) setHistory(data.sessions); });
    return () => { active = false; };
  }, []);
  async function createQuote() { setBusy(true); setNotice(null); const response = await fetch("/api/cashout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amountUsdc: amount }) }); const data = await response.json() as { error?: string; session?: Quote }; if (response.ok && data.session) { setQuote(data.session); setNotice(vi ? "Báo giá sandbox đã sẵn sàng. Chưa có tiền hay dữ liệu ngân hàng nào được chuyển." : "Your sandbox quote is ready. No funds or bank details have been transferred."); await load(); } else setNotice(data.error || (vi ? "Không thể tạo báo giá." : "Unable to create a quote.")); setBusy(false); }
  async function complete() { if (!quote) return; setBusy(true); const response = await fetch(`/api/cashout/${quote.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "complete_sandbox" }) }); const data = await response.json() as { error?: string }; setNotice(response.ok ? (vi ? "Đã hoàn tất mô phỏng. Không có chuyển khoản ngân hàng thật." : "Sandbox flow completed. No real bank transfer was made.") : data.error || (vi ? "Không thể hoàn tất sandbox." : "Unable to complete sandbox.")); if (response.ok) await load(); setBusy(false); }
  return <div className="workspace-product-content cashout-workspace"><div className="app-welcome"><div><span>{vi ? "CASH-OUT SANDBOX" : "CASH-OUT SANDBOX"}</span><h1>{vi ? "Thử hành trình USDC → VND, không chuyển tiền thật." : "Explore USDC → VND without moving real money."}</h1><p>{vi ? "Đây là prototype trải nghiệm off-ramp cho giám khảo và người dùng non-tech. SkillBridge chỉ tính báo giá mô phỏng; không nhận thông tin ngân hàng, không gọi đối tác thanh toán và không rút tiền khỏi ví." : "This is an off-ramp experience prototype for judges and non-technical users. SkillBridge only calculates a simulated quote; it collects no bank information, calls no payment partner and never withdraws from your wallet."}</p></div><div className="identity-card"><small>{vi ? "TRẠNG THÁI" : "STATUS"}</small><strong className="metric-number">TEST</strong><b>{vi ? "Không có giao dịch thật" : "No real transaction"}</b></div></div>
    <section className="app-panel cashout-panel"><div><span className="panel-kicker">{vi ? "BƯỚC 1 · NHẬP SỐ TIỀN" : "STEP 1 · ENTER AMOUNT"}</span><h2>{vi ? "Xem trước số VND nhận được" : "Preview the VND amount"}</h2><p>{vi ? "Tỷ giá sandbox được cấu hình riêng trong môi trường triển khai. Đây không phải báo giá thị trường hay lời mời giao dịch." : "The sandbox rate is configured per deployment. It is neither a market quote nor an invitation to transact."}</p></div><div className="stack-form"><label>{vi ? "Số USDC muốn mô phỏng" : "USDC to simulate"}<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="25" /></label><button className="button button-primary" type="button" disabled={busy || !amount.trim()} onClick={() => void createQuote()}>{vi ? "Tạo báo giá sandbox" : "Create sandbox quote"}</button></div></section>
    {quote && <section className="cashout-quote" aria-live="polite"><div><span>{vi ? "BÁO GIÁ MÔ PHỎNG" : "SIMULATED QUOTE"}</span><strong>{quote.amountUsdc} USDC</strong><small>{vi ? `Tỷ giá giả định ${vnd(quote.rate)} / USDC` : `Assumed rate ${vnd(quote.rate)} / USDC`}</small></div><dl><div><dt>{vi ? "Giá trị quy đổi" : "Converted value"}</dt><dd>{vnd(quote.estimatedVnd)}</dd></div><div><dt>{vi ? "Phí mô phỏng" : "Simulated fee"}</dt><dd>− {vnd(quote.feeVnd)}</dd></div><div><dt>{vi ? "Bạn sẽ nhận (mô phỏng)" : "You receive (simulated)"}</dt><dd>{vnd(quote.netVnd)}</dd></div></dl><div className="cashout-sandbox-callout"><strong>{vi ? "Không liên kết ngân hàng. Không gửi USDC. Không có thanh toán thật." : "No bank linked. No USDC sent. No real payment."}</strong><button className="button button-secondary" type="button" disabled={busy || quote.status === "sandbox_complete"} onClick={() => void complete()}>{quote.status === "sandbox_complete" ? (vi ? "Đã hoàn tất mô phỏng" : "Sandbox completed") : (vi ? "Hoàn tất mô phỏng" : "Complete simulation")}</button></div></section>}
    <section className="app-panel cashout-history"><div><span className="panel-kicker">{vi ? "LỊCH SỬ CỦA BẠN" : "YOUR HISTORY"}</span><h2>{vi ? "Các phiên sandbox gần đây" : "Recent sandbox sessions"}</h2></div>{history.length ? <div className="cashout-history-list">{history.map((item) => <article key={item.id}><div><strong>{item.amount_usdc} USDC</strong><span>{item.provider_reference}</span></div><div><b>{vnd(item.net_vnd)}</b><small>{item.status === "sandbox_complete" ? (vi ? "Đã hoàn tất mô phỏng" : "Simulation completed") : (vi ? "Báo giá sẵn sàng" : "Quote ready")}</small></div></article>)}</div> : <p className="field-hint">{vi ? "Chưa có phiên mô phỏng nào." : "No sandbox sessions yet."}</p>}</section>
    {notice && <p className="app-notice" role="status">{notice}</p>}
  </div>;
}
