"use client";

import { LanguageSwitcher, useLanguage } from "./i18n";
import { GoldenFlow } from "./golden-flow";

export function HomeCopy() {
  const { t } = useLanguage();
  return <main><header className="site-header page-shell"><a className="wordmark" href="#top" aria-label="SkillBridge Vietnam"><span className="wordmark-mark" aria-hidden="true">S</span><span>SkillBridge</span><small>VIETNAM</small></a><nav aria-label={t("home.navHow")}><a href="#demo">{t("home.navDemo")}</a><a href="/app">{t("home.navProduct")}</a><a href="#trust">{t("home.navHow")}</a><a href="#pilot">{t("home.navPilot")}</a></nav><div className="topbar-actions"><LanguageSwitcher /><a className="header-cta" href="/auth">{t("home.login")}</a></div></header>
    <section className="hero page-shell" id="top"><div className="hero-copy"><div className="eyebrow"><span /> {t("home.eyebrow")}</div><h1>{t("home.heroTitle")}</h1><p className="hero-lede">{t("home.heroDescription")}</p><div className="hero-actions"><a className="button button-primary" href="/auth">{t("home.start")}</a><a className="text-link" href="#trust">{t("home.trustArchitecture")}</a></div><div className="hero-proof" aria-label={t("home.trustArchitecture")}><span>{t("home.aiEvidence")}</span><span>{t("home.humanLoop")}</span><span>{t("home.solanaProof")}</span></div></div><div className="hero-object" aria-label={t("home.heroTitle")}><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="proof-card proof-card-main"><div className="card-kicker">{t("home.cardProof")}</div><div className="score-ring"><strong>87</strong><span>/100</span></div><h2>{t("home.cardScore")}</h2><p>{t("home.cardChallenge")}</p><div className="proof-meta"><span>{t("home.humanApproved")}</span><span>{t("home.evidenceLinked")}</span></div></div><div className="proof-card proof-card-mini top"><span className="mini-icon">01</span><div><strong>{t("home.cardBuild")}</strong><small>{t("home.build")}</small></div></div><div className="proof-card proof-card-mini bottom"><span className="mini-icon accent">02</span><div><strong>{t("home.cardUnlock")}</strong><small>{t("home.unlock")}</small></div></div></div></section>
    <section className="trust-strip"><div className="page-shell trust-steps">{[["01", t("home.learnLabel"), t("home.learn")], ["02", t("home.buildLabel"), t("home.buildStep")], ["03", t("home.proveLabel"), t("home.prove")], ["04", t("home.unlockLabel"), t("home.unlockStep")]].map(([number, label, detail]) => <div className="trust-step" key={number}><span>{number}</span><div><strong>{label}</strong><small>{detail}</small></div></div>)}</div></section>
    <section className="demo-section page-shell" id="demo"><div className="section-heading"><div><div className="eyebrow"><span /> {t("home.demoEyebrow")}</div><h2>{t("home.demoTitle")}</h2></div><p>{t("home.demoDescription")}</p></div><GoldenFlow /></section>
    <section className="trust-architecture" id="trust"><div className="page-shell"><div className="section-heading light"><div><div className="eyebrow"><span /> {t("home.trustEyebrow")}</div><h2>{t("home.trustTitle")}</h2></div><p>{t("home.trustDescription")}</p></div><div className="architecture-grid"><article><span>AI</span><h3>{t("home.assessmentContract")}</h3><p>{t("home.assessmentDescription")}</p><small>{t("home.contractEvals")}</small></article><article><span>H</span><h3>{t("home.humanReview")}</h3><p>{t("home.humanDescription")}</p><small>{t("home.auditAppeal")}</small></article><article><span>S</span><h3>{t("home.solanaProofTitle")}</h3><p>{t("home.solanaDescription")}</p><small>{t("home.noPii")}</small></article><article className="architecture-outcome"><span>↗</span><h3>{t("home.accessTitle")}</h3><p>{t("home.accessDescription")}</p><small>{t("home.verifyLoop")}</small></article></div></div></section>
    <section className="pilot-section page-shell" id="pilot"><div className="pilot-card"><div><div className="eyebrow"><span /> {t("home.pilotEyebrow")}</div><h2>{t("home.pilotTitle")}</h2></div><div className="pilot-copy"><p>{t("home.pilotDescription")}</p><a className="button button-dark" href="mailto:pilot@skillbridge.vn">{t("home.designPartner")}</a></div></div></section>
    <footer className="site-footer page-shell"><div className="wordmark"><span className="wordmark-mark">S</span><span>SkillBridge</span></div><p>{t("home.footerTagline")} <a href="/privacy">{t("home.data")}</a> · <a href="/terms">{t("home.terms")}</a> · <a href="/risk">{t("home.risk")}</a></p><span>{t("home.builtFor")}</span></footer>
  </main>;
}
