"use client";

import { useEffect, useState } from "react";
import { translateStatus, useLanguage } from "./i18n";
import { ContentSkeleton, LoadFailure } from "./loading-ui";

type Membership = { id: string; organization_id: string; organization_name: string; organization_kind: string; role: string };
type University = { id: string; name: string };
type Opportunity = { id: string; title: string; description: string; organization_name: string; required_issuer_name: string; minimum_score: string; status: string; latest_decision: string | null; policy_address: string | null; policy_tx: string | null };
type AccessResult = { decision: string; reason: string; receiptAddress: string | null; recordTx: string | null };
const explorerAddress = (value: string) => `https://explorer.solana.com/address/${value}?cluster=devnet`;
const explorerTransaction = (value: string) => `https://explorer.solana.com/tx/${value}?cluster=devnet`;

export function OpportunitiesWorkspace({ memberships, universities }: { memberships: Membership[]; universities: University[] }) {
  const { t } = useLanguage();
  const businesses = memberships.filter((item) => item.organization_kind === "business" && ["business_admin", "challenge_manager"].includes(item.role));
  const [items, setItems] = useState<Opportunity[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(false); const [organizationId, setOrganizationId] = useState(businesses[0]?.organization_id ?? ""); const [issuerId, setIssuerId] = useState(universities[0]?.id ?? ""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [minimumScore, setMinimumScore] = useState(80); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [lastAccess, setLastAccess] = useState<AccessResult | null>(null);
  async function load() { const response = await fetch("/api/opportunities", { cache: "no-store" }); if (response.ok) setItems(((await response.json()) as { opportunities: Opportunity[] }).opportunities); }
  useEffect(() => { let active = true; fetch("/api/opportunities", { cache: "no-store" }).then((response) => response.ok ? response.json() as Promise<{ opportunities: Opportunity[] }> : Promise.reject(new Error("load"))).then((data) => { if (active) setItems(data.opportunities); }).catch(() => { if (active) setLoadError(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function create() { setBusy(true); setLastAccess(null); const response = await fetch("/api/opportunities", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ organizationId, title, description, requiredIssuerOrganizationId: issuerId, minimumScore }) }); const data = await response.json() as { error?: string }; setNotice(response.ok ? t("opportunity.created") : data.error ?? t("opportunity.createError")); if (response.ok) { setTitle(""); setDescription(""); await load(); } setBusy(false); }
  async function verify(id: string) { setBusy(true); setLastAccess(null); const response = await fetch(`/api/opportunities/${id}/verify`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); const data = await response.json() as { access?: AccessResult; error?: string }; if (data.access) { setLastAccess(data.access); setNotice(`${data.access.decision.toUpperCase()}: ${data.access.reason}`); } else setNotice(data.error ?? t("opportunity.verifyError")); await load(); setBusy(false); }
  if (loading) return <div id="workspace-main" tabIndex={-1} className="workspace-product-content"><ContentSkeleton delayed variant="list" /></div>;
  if (loadError) return <div id="workspace-main" tabIndex={-1} className="workspace-product-content"><LoadFailure /></div>;
  return <div id="workspace-main" tabIndex={-1} className="workspace-product-content"><div className="app-welcome"><div><span>{t("opportunity.kicker")}</span><h1>{t("opportunity.title")}</h1><p>{t("opportunity.description")}</p></div><div className="identity-card"><small>{t("opportunity.active")}</small><strong className="metric-number">{items.filter((item) => item.status === "active").length}</strong><b>{t("opportunity.liveVerification")}</b></div></div>
    {businesses.length > 0 && <section className="app-panel opportunity-builder"><div><span className="panel-kicker">{t("opportunity.newPolicy")}</span><h2>{t("opportunity.createGate")}</h2><p>{t("opportunity.policyDescription")}</p></div><div className="stack-form"><select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}>{businesses.map((item) => <option value={item.organization_id} key={item.id}>{item.organization_name}</option>)}</select><select value={issuerId} onChange={(event) => setIssuerId(event.target.value)}>{universities.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder={t("opportunity.titlePlaceholder")} /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder={t("opportunity.descriptionPlaceholder")} /><label>{t("opportunity.minimumScore")}<input type="number" min="0" max="100" value={minimumScore} onChange={(event) => setMinimumScore(Number(event.target.value))} /></label><button className="button button-dark" disabled={busy || !issuerId || !title.trim()} onClick={create}>{t("opportunity.createPolicy")}</button></div></section>}
    <section className="opportunity-list">{items.map((item) => <article key={item.id}><div className="entity-top"><span>{item.organization_name}</span><b>{translateStatus(t, item.latest_decision ?? item.status)}</b></div><h2>{item.title}</h2><p>{item.description}</p><dl><div><dt>{t("opportunity.trustedIssuer")}</dt><dd>{item.required_issuer_name}</dd></div><div><dt>{t("opportunity.minScore")}</dt><dd>{item.minimum_score}</dd></div></dl>{item.policy_address && <div className="chain-actions"><a href={explorerAddress(item.policy_address)} target="_blank" rel="noreferrer">{t("opportunity.policyAccount")}</a>{item.policy_tx && <a href={explorerTransaction(item.policy_tx)} target="_blank" rel="noreferrer">{t("opportunity.createTx")}</a>}</div>}{item.status === "active" && <button className="button button-primary" disabled={busy} onClick={() => verify(item.id)}>{t("opportunity.verifyUnlock")}</button>}</article>)}</section>{notice && <p className="app-notice">{notice}</p>}{lastAccess?.receiptAddress && <div className="chain-actions access-receipt-links"><a href={explorerAddress(lastAccess.receiptAddress)} target="_blank" rel="noreferrer">{t("opportunity.accessReceipt")}</a>{lastAccess.recordTx && <a href={explorerTransaction(lastAccess.recordTx)} target="_blank" rel="noreferrer">{t("opportunity.recordTx")}</a>}</div>}</div>;
}
