"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useLanguage } from "../../i18n/i18n";
import type { PackContent, PortfolioSource } from "../../../shared/validation/portfolio";
import type { CareerDraft } from "../../../shared/validation/career-assistance";
import styles from "./portfolio.module.css";
type Source=PortfolioSource&{verification?:{state:string;checkedAt:string}|null};
type Pack={id:string;owner:boolean;version:number;publishedVersion:number|null;content:PackContent;sources:Source[];staleSources:boolean};
type Catalog={packs:Array<{id:string;title:string;current_version:number;published_version:number|null}>;sources:PortfolioSource[];applications:Array<{id:string;title:string}>;opportunities?:Array<{id:string;title:string;description:string;requirements:string|null}>};
type Usage={trial:{active:boolean;expiresAt:string|null};packLimit:number;packCount:number;aiDailyLimit:number;aiUsed:number};
async function api<T=unknown>(url:string,method="GET",body?:unknown){
  const r=await fetch(url,{method,cache:"no-store",...(body?{headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{})});
  const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(String(r.status));return data as T;
}
const key=(s:{kind:string;id:string})=>s.kind+":"+s.id;
const mergeSources=(catalog:Catalog,pack:Pack):Catalog=>({...catalog,sources:[...catalog.sources,...pack.sources.filter(s=>!catalog.sources.some(c=>key(c)===key(s)))]});
function sourceText(s:PortfolioSource,vi:boolean){
  try{const d=JSON.parse(s.content);return [d.title,d.issuer,(d.score??d.totalScore)!==undefined?`${vi?"Điểm chính thức":"Official score"}: ${d.score??d.totalScore}`:"",d.summary].filter(Boolean).join("\n");}catch{return s.content;}
}
export function PortfolioWorkspace({id,publicView=false}:{id?:string;publicView?:boolean}){
  const router=useRouter();
  const {locale}=useLanguage(),vi=locale==="vi";
  const [catalog,setCatalog]=useState<Catalog|null>(null),[pack,setPack]=useState<Pack|null>(null),[usage,setUsage]=useState<Usage|null>(null);
  const [draft,setDraft]=useState<PackContent>({title:"",purpose:"employment",target:"",introduction:""});
  const [selected,setSelected]=useState<string[]>([]),[application,setApplication]=useState("");
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
  const [aiConsent,setAiConsent]=useState(false),[shareConsent,setShareConsent]=useState(false),[ai,setAi]=useState<CareerDraft|null>(null),[aiId,setAiId]=useState("");
  const error=(e:unknown)=>{const code=e instanceof Error?e.message:"";setNotice(code==="429"?(vi?"Đã hết lượt hoặc thao tác quá nhanh. Hãy kiểm tra hạn mức.":"Limit reached. Check usage before retrying."):code==="409"?(vi?"Phiên bản, nguồn hoặc trạng thái đã thay đổi. Tải lại và lưu nguồn hiện tại trước.":"Version, evidence or state changed. Reload and save current sources first."):code==="403"?(vi?"Chưa có quyền sử dụng nguồn hoặc gói thử nghiệm đã hết hạn.":"Evidence permission is missing or the trial has ended."):code==="503"?(vi?"AI chưa sẵn sàng. Bạn vẫn có thể chỉnh hồ sơ thủ công.":"AI is unavailable. Manual editing remains available."):(vi?"Không hoàn thành được thao tác. Kiểm tra kết nối hoặc quyền truy cập rồi thử lại.":"Could not complete this action. Check connection/access and retry."));};
  async function load(){
    if(!publicView){const [c,u]=await Promise.all([api<Catalog>("/api/portfolio/packs"),api<Usage>("/api/features/usage")]);setCatalog(c);setUsage(u);}
    if(id){const p=await api<Pack>("/api/portfolio/packs/"+encodeURIComponent(id));setPack(p);setDraft(p.content);setSelected(p.sources.map(key));setCatalog(c=>c?mergeSources(c,p):null);}
  }
  useEffect(()=>{let live=true;const run=async()=>{try{
    const p=id?await api<Pack>("/api/portfolio/packs/"+encodeURIComponent(id)+(publicView?"?public=1":"")):null;
    const c=publicView?null:await api<Catalog>("/api/portfolio/packs"),u=publicView?null:await api<Usage>("/api/features/usage");
    if(!live)return;setCatalog(c&&p?mergeSources(c,p):c);setUsage(u);if(p){setPack(p);setDraft(p.content);setSelected(p.sources.map(key));}
  }catch{if(live)setNotice(vi?"Không tải được hồ sơ hoặc bạn chưa có quyền xem.":"Portfolio unavailable or access not granted.");}finally{if(live)setLoading(false);}};void run();return()=>{live=false;};},[id,publicView,vi]);
  async function perform(action:()=>Promise<void>){setBusy(true);setNotice("");try{await action();}catch(e){error(e);}finally{setBusy(false);}}
  const editable=!publicView&&(!id||pack?.owner);
  function change<K extends keyof PackContent>(field:K,value:PackContent[K]){setDraft(d=>({...d,[field]:value}));setShareConsent(false);setAiConsent(false);setAi(null);}
  async function save(){const payload={...draft,sources:selected.flatMap(k=>(catalog?.sources??[]).filter(s=>key(s)===k)).map(s=>({kind:s.kind,id:s.id})),version:pack?.version};
    const saved=await api<{id:string;version:number}>(id?"/api/portfolio/packs/"+id:"/api/portfolio/packs",id?"PATCH":"POST",payload);
    if(!id){router.push("/app/profile/packs/"+saved.id);return;}await load();setAi(null);setShareConsent(false);setNotice(vi?"Đã lưu phiên bản mới. Bản đã chia sẻ trước đó không bị ghi đè.":"New version saved. Earlier shared versions were not overwritten.");}
  async function share(action:"publish"|"application"|"revoke"){
    await api(`/api/portfolio/packs/${id}/share`,"POST",{action,applicationId:application,consent:shareConsent,version:pack?.version});await load();setShareConsent(false);setNotice(action==="revoke"?(vi?"Đã tắt các quyền chia sẻ. Bản người khác đã tải không thể thu hồi.":"Sharing revoked. Previously downloaded copies cannot be recalled."):(vi?"Đã chia sẻ đúng phiên bản đã lưu.":"Saved version shared."));
  }
  async function generate(){const result=await api<{id:string;status:string;result:CareerDraft}>("/api/career-assistance","POST",{packId:id,version:pack?.version,locale,consent:aiConsent});setAiId(result.id);if(result.status==="complete")setAi(result.result);else setNotice(vi?"Đang xử lý. Dùng nút kiểm tra kết quả, không cần gửi lại.":"Processing. Check the result rather than submitting again.");setUsage(await api<Usage>("/api/features/usage"));}
  if(loading)return <div id={publicView?undefined:"workspace-main"} tabIndex={-1} className={styles.workspace} role="status">{vi?"Đang chuẩn bị hồ sơ…":"Preparing portfolio…"}</div>;
  return <div id={publicView?undefined:"workspace-main"} tabIndex={-1} className={styles.workspace}>
    <header><p className={styles.muted}>{vi?"HỒ SƠ THEO MỤC TIÊU":"EVIDENCE PORTFOLIOS"}</p><h1>{publicView?pack?.content.title??(vi?"Hồ sơ không khả dụng":"Portfolio unavailable"):id?(vi?"Chuẩn bị hồ sơ của bạn":"Prepare your portfolio"):(vi?"Bằng chứng cho cơ hội tiếp theo":"Evidence for your next opportunity")}</h1><p>{vi?"Bạn chọn bằng chứng và người được xem. AI hỗ trợ viết nháp, không cấp thành tích hay quyết định tuyển dụng.":"Choose your evidence and audience. AI drafts; it does not award achievements or make hiring decisions."}</p>{!publicView&&<Link href="/app/profile">← {vi?"Hồ sơ của tôi":"My profile"}</Link>}</header>
    {notice&&<p className={styles.notice} role="status">{notice}</p>}
    {usage&&<section className={`${styles.panel} ${styles.noPrint}`}><h2>{vi?"Quyền lợi và mức sử dụng":"Features and usage"}</h2><p>{usage.trial.active?(vi?"Personal Plus · thử nghiệm miễn phí":"Personal Plus · free launch trial"):(vi?"Core · hồ sơ cơ bản":"Core · basic portfolios")}</p><p>{vi?"Bộ hồ sơ":"Portfolios"}: {usage.packCount}/{usage.packLimit} · AI: {usage.aiUsed}/{usage.aiDailyLimit} {vi?"lượt hôm nay":"today"}</p><p className={styles.muted}>{vi?"Đây là gói thử nghiệm, chưa thu phí. Chứng nhận, xác minh và nhận thưởng không bị khóa khi hết gói.":"Trial access, no charges. Credentials, verification and allocated claims remain accessible after expiry."}{usage.trial.expiresAt&&` · ${new Date(usage.trial.expiresAt).toLocaleDateString(locale)}`}</p></section>}
    {!id&&catalog&&<section className={styles.panel}><h2>{vi?"Các bộ hồ sơ đã lưu":"Saved portfolios"}</h2>{!catalog.packs.length?<p>{vi?"Chưa có bộ hồ sơ. Bắt đầu bằng mục tiêu của bạn ở dưới.":"No portfolios yet. Start with your goal below."}</p>:catalog.packs.map(p=><div className={styles.source} key={p.id}><Link href={`/app/profile/packs/${p.id}`}>{p.title}</Link><small> · v{p.current_version}</small></div>)}</section>}
    {editable&&<div className={`${styles.grid} ${styles.noPrint}`}><section className={`${styles.panel} ${styles.stack}`}><h2>{vi?"1. Mục tiêu và giới thiệu":"1. Goal and introduction"}</h2><label>{vi?"Tên bộ hồ sơ":"Portfolio title"}<input maxLength={120} value={draft.title} onChange={e=>change("title",e.target.value)}/></label><label>{vi?"Mục tiêu":"Purpose"}<select value={draft.purpose} onChange={e=>change("purpose",e.target.value as PackContent["purpose"])}><option value="employment">{vi?"Ứng tuyển việc làm":"Employment"}</option><option value="freelance">{vi?"Giới thiệu dịch vụ freelance":"Freelance services"}</option></select></label><label>{vi?"Điền từ cơ hội đang mở (tùy chọn)":"Use an open opportunity (optional)"}<select defaultValue="" onChange={e=>{const op=catalog?.opportunities?.find(o=>o.id===e.target.value);if(op)change("target",[op.title,op.description,op.requirements].filter(Boolean).join("\n").slice(0,4000));}}><option value="">{vi?"Tự nhập mục tiêu":"Enter my own target"}</option>{catalog?.opportunities?.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>{vi?"Yêu cầu hoặc mô tả mục tiêu":"Requirements or target description"}<textarea maxLength={4000} value={draft.target} onChange={e=>change("target",e.target.value)}/></label><label>{vi?"Giới thiệu (do bạn viết/duyệt)":"Introduction (authored/approved by you)"}<textarea maxLength={4000} value={draft.introduction} onChange={e=>change("introduction",e.target.value)}/></label><div className={styles.stack}>{selected.map((k,i)=><div className={styles.row} key={k}><span>{i+1}. {catalog?.sources.find(s=>key(s)===k)?.title}</span><button type="button" disabled={i===0} onClick={()=>setSelected(a=>{const b=[...a];[b[i-1],b[i]]=[b[i],b[i-1]];return b;})}>{vi?"Lên":"Up"}</button><button type="button" disabled={i===selected.length-1} onClick={()=>setSelected(a=>{const b=[...a];[b[i+1],b[i]]=[b[i],b[i+1]];return b;})}>{vi?"Xuống":"Down"}</button></div>)}</div><button className={styles.primary} disabled={busy||draft.title.trim().length<2} onClick={()=>void perform(save)}>{busy?(vi?"Đang xử lý…":"Working…"):(vi?"Lưu phiên bản":"Save version")}</button></section>
      <aside className={styles.panel}><h2>{vi?"2. Chọn bằng chứng":"2. Select evidence"}</h2><p className={styles.muted}>{vi?"Tối đa 5 nguồn. Không tự chia sẻ tệp gốc. Tóm tắt đánh giá cần người đánh giá cho phép trước khi chia sẻ hoặc gửi AI.":"Up to 5 sources. Original files are not shared. Review summaries need reviewer permission before sharing or AI use."}</p>{!catalog?.sources.length&&<p>{vi?"Chưa có kết quả đánh giá hoặc chứng nhận. Bạn vẫn có thể viết hồ sơ tự giới thiệu.":"No reviewed evidence or credentials yet. You can still write a self-described portfolio."}</p>}{catalog?.sources.map(s=><div className={styles.source} key={key(s)}><label className={styles.check}><input type="checkbox" checked={selected.includes(key(s))} disabled={!selected.includes(key(s))&&selected.length>=5} onChange={e=>{setSelected(x=>e.target.checked?[...x,key(s)]:x.filter(k=>k!==key(s)));setShareConsent(false);setAiConsent(false);}}/><span>{s.title}<br/><small>{s.kind==="credential"?(vi?"Chứng nhận · cần kiểm tra hiệu lực":"Credential · validity check required"):(vi?"Đánh giá của con người":"Human review")}</small></span></label>{!s.shareable&&<p className={styles.muted}>{vi?"Chưa được phép chia sẻ hoặc nguồn không còn hiệu lực.":"Sharing is not permitted or this source is inactive."}</p>}</div>)}</aside></div>}
    {pack&&<section className={styles.panel}><div className={styles.row}><h2>{vi?"Bản đã lưu":"Saved version"} · {pack.version}</h2><span className={styles.badge}>{vi?"Giới thiệu do chủ hồ sơ duyệt":"Owner-authored introduction"}</span><button onClick={()=>window.print()}>{vi?"In / lưu PDF":"Print / save PDF"}</button></div>{pack.staleSources&&<p className={`${styles.notice} ${styles.warning}`}>{vi?"Nguồn đã thay đổi. Chọn lại nguồn và lưu phiên bản mới trước khi chia sẻ hoặc dùng AI.":"Evidence changed. Select current sources and save a new version before sharing or AI use."}</p>}<h3>{pack.content.title}</h3><p style={{whiteSpace:"pre-wrap"}}>{pack.content.introduction||"—"}</p>{pack.sources.map((s,index)=><article id={`source-S${index+1}`} className={styles.source} key={key(s)}><span className={styles.badge}>{s.kind==="assessment"?(vi?"Kết quả người đánh giá":"Human assessment"):s.verification?.state==="active"?(vi?"Đã kiểm tra on-chain":"Checked on-chain"):(vi?"Chưa xác minh / không còn hiệu lực":"Unverified / inactive")}</span><div className={styles.proof}>{sourceText(s,vi)}</div><details><summary>{vi?"Xem nội dung nguồn đầy đủ":"Inspect full source content"}</summary><pre className={styles.proof}>{s.content}</pre></details>{s.attestation&&<a href={`https://explorer.solana.com/address/${s.attestation}?cluster=devnet`} target="_blank" rel="noreferrer">Solana Explorer</a>}{s.verification&&<small> · {new Date(s.verification.checkedAt).toLocaleString(locale)}</small>}</article>)}<p className={styles.muted}>{vi?"Bản in chỉ phản ánh thời điểm xem. Cần kiểm tra lại hiệu lực chứng nhận.":"Printed copies reflect this observation only. Recheck credential validity."}</p></section>}
    {editable&&pack&&<div className={`${styles.grid} ${styles.noPrint}`}><section className={`${styles.panel} ${styles.stack}`}><h2>{vi?"3. AI hỗ trợ bản đã lưu":"3. AI assistance for the saved version"}</h2><p>{vi?"Chỉ gửi mục tiêu và nội dung các nguồn hiển thị trong bản đã lưu; không gửi tệp gốc. Bạn phải kiểm tra và duyệt mọi nhận định.":"Only the saved target and selected source content are sent, never original files. Review and approve every claim."}</p><label className={styles.check}><input type="checkbox" checked={aiConsent} onChange={e=>setAiConsent(e.target.checked)}/>{vi?"Tôi đồng ý gửi các nguồn này cho OpenRouter để tạo bản nháp.":"I consent to sending these sources to OpenRouter for a draft."}</label><button disabled={busy||!aiConsent||pack.staleSources||!pack.sources.length} onClick={()=>void perform(generate)}>{vi?"Tạo bản nháp có nguồn":"Generate grounded draft"}</button>{aiId&&<button disabled={busy} onClick={()=>void perform(async()=>{const r=await api<{status:string;result:CareerDraft|null}>("/api/career-assistance/"+aiId);setAi(r.result);setNotice(r.status==="complete"?(vi?"Đã có bản nháp.":"Draft ready."):(vi?"Chưa có kết quả hoàn tất. Có thể thử lại nếu lượt trước đã bị gián đoạn.":"No completed result yet. Retry if the previous request was interrupted."));})}>{vi?"Kiểm tra kết quả":"Check result"}</button>}{ai&&<><p className={styles.badge}>{vi?"Bản nháp AI — chưa được bạn duyệt":"AI draft — not yet approved"}</p>{ai.claims.map((c,i)=><div className={styles.source} key={i}><p>{c.text}</p><blockquote>{c.quote}</blockquote><a href={`#source-${c.sourceId}`}>{vi?"Mở nguồn":"Open source"} · {c.sourceId}</a></div>)}<h3>{vi?"Chưa tìm thấy trong nguồn đã chọn":"Not found in selected evidence"}</h3><ul>{ai.gaps.map((g,i)=><li key={i}>{g}</li>)}</ul><h3>{vi?"Câu hỏi luyện tập":"Practice questions"}</h3><ul>{ai.questions.map((q,i)=><li key={i}>{q}</li>)}</ul><button onClick={()=>change("introduction",ai.claims.map(c=>c.text).join("\n\n"))}>{vi?"Đưa vào ô giới thiệu để tôi sửa và lưu":"Use in introduction for my review and save"}</button></>}</section>
      <section className={`${styles.panel} ${styles.stack}`}><h2>{vi?"4. Chia sẻ có kiểm soát":"4. Controlled sharing"}</h2><p>{vi?"Chỉ chia sẻ phiên bản đã lưu ở trên. Mặc định hồ sơ riêng tư; có thể thu hồi quyền xem, nhưng không thu hồi bản đã tải.":"Share only the saved version above. Private by default; access can be revoked but downloaded copies cannot be recalled."}</p><label className={styles.check}><input type="checkbox" checked={shareConsent} onChange={e=>setShareConsent(e.target.checked)}/>{vi?"Tôi đã kiểm tra bản đã lưu và đồng ý chia sẻ các nguồn đã chọn.":"I reviewed the saved version and consent to sharing its selected sources."}</label><button disabled={busy||!shareConsent||pack.staleSources} onClick={()=>void perform(()=>share("publish"))}>{vi?"Công khai phiên bản này":"Publish this version"}</button>{pack.publishedVersion&&<Link href={`/portfolio/${pack.id}`} target="_blank">{vi?"Mở trang chia sẻ công khai":"Open public portfolio"} · v{pack.publishedVersion}</Link>}<label>{vi?"Hoặc chỉ gửi cho nơi đã ứng tuyển":"Or share only with an existing application"}<select value={application} onChange={e=>setApplication(e.target.value)}><option value="">{vi?"Chọn cơ hội":"Choose opportunity"}</option>{catalog?.applications.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><button disabled={busy||!shareConsent||!application||pack.staleSources} onClick={()=>void perform(()=>share("application"))}>{vi?"Cấp quyền cho doanh nghiệp trong 30 ngày":"Grant employer access for 30 days"}</button><button disabled={busy} onClick={()=>void perform(()=>share("revoke"))}>{vi?"Thu hồi mọi quyền chia sẻ của bộ này":"Revoke all sharing for this portfolio"}</button></section></div>}
  </div>;
}
